### ISSUE TITLE
Serverless meeting demo does not build using steps outlined in README.md

### ISSUE THREAD

**Issue by aburnson** [aws/amazon-chime-sdk-component-library-react#472]
**Describe the bug**

I ran into issues deploying the serverless meeting demo using the instructions [here](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#to-deploy-the-serverless-device-demo). The actual steps I needed to take to build the demo were:

```
# configure AWS credentials
# install yalc globally:  npm i yalc -g
git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
cd amazon-chime-sdk-component-library-react
npm install
cd demo/meeting
# manually update demo/meeting/package.json to use ^17.0.1 for @types/react, @types/react-dom, react, react-dom
npm run build
cd serverless
node ./deploy.js -r us-east-1 -b <mybucket> -s <mystack>
```

**To Reproduce**

I followed the steps [here](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#to-deploy-the-serverless-device-demo):

```
# configure AWS credentials
# install yalc globally:  npm i yalc -g
git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
cd amazon-chime-sdk-component-library-react/demo/meeting/serverless
node ./deploy.js -r us-east-1 -b <mybucket> -s <mystack>
```

**Expected behavior**

Expected demo to deploy.

**Actual behavior**

```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module '/Users/aburnson/Desktop/demo2/amazon-chime-sdk-component-library-react/demo/meeting/deploy.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by devalevenkatesh** [comment]
Hello @aburnson,

I have updated the README with the clear steps as you mentioned. However, I do not have to update @types/react, @types/react-dom, react, react-dom packages to ^17.0.1.

While upgrading the library for react@17, we had tested if our meeting demo (and deployment) is working fine even if it is on react@16.x.

Please let me know if the updated steps work for you.

**Comment by aburnson** [comment]
I followed the steps in https://github.com/aws/amazon-chime-sdk-component-library-react/pull/474 and still got the dependency resolution failure:

```
aburnson@ test % git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
Cloning into 'amazon-chime-sdk-component-library-react'...
remote: Enumerating objects: 196, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 8183 (delta 81), reused 159 (delta 67), pack-reused 7987
Receiving objects: 100% (8183/8183), 9.01 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (5018/5018), done.
```

```
aburnson@ test % cd amazon-chime-sdk-component-library-react
aburnson@ amazon-chime-sdk-component-library-react % npm install

added 2405 packages, and audited 2406 packages in 45s

found 0 vulnerabilities
```

```
aburnson@ amazon-chime-sdk-component-library-react % cd demo/meeting 
aburnson@ meeting % npm run build

> chime-sdk-meeting-demo@0.1.0 build
> npm run deps && yalc add amazon-chime-sdk-component-library-react && npm install && npm run build:fast


> chime-sdk-meeting-demo@0.1.0 deps
> cd ../.. && npm run build && yalc publish


> amazon-chime-sdk-component-library-react@2.2.0 build
> rollup -c


src/index.ts → lib/index.js, lib/index.esm.js...
(!) Circular dependencies
src/index.ts -> src/components/ui/Chat/ChatBubble/ChatBubbleContainer.tsx -> src/index.ts
src/providers/AudioVideoProvider/index.tsx -> src/providers/MeetingProvider/index.tsx -> src/providers/AudioVideoProvider/index.tsx
src/providers/MeetingProvider/index.tsx -> src/providers/RosterProvider/index.tsx -> src/providers/MeetingProvider/index.tsx
...and 8 more
created lib/index.js, lib/index.esm.js in 50.2s
amazon-chime-sdk-component-library-react@2.2.0+c9ddf741 published in store.
Package amazon-chime-sdk-component-library-react@2.2.0+c9ddf741 added ==> /Users/aburnson/Desktop/test/amazon-chime-sdk-component-library-react/demo/meeting/node_modules/amazon-chime-sdk-component-library-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"^16.12.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from amazon-chime-sdk-component-library-react@2.2.0+c9ddf741
npm ERR! .yalc/amazon-chime-sdk-component-library-react
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/aburnson/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aburnson/.npm/_logs/2021-04-05T16_30_30_538Z-debug.log
npm ERR! code 1
npm ERR! path /Users/aburnson/Desktop/test/amazon-chime-sdk-component-library-react/demo/meeting
npm ERR! command failed
npm ERR! command sh -c npm run deps && yalc add amazon-chime-sdk-component-library-react && npm install && npm run build:fast

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aburnson/.npm/_logs/2021-04-05T16_30_30_569Z-debug.log
```

**Comment by devalevenkatesh** [comment]
I see, so you are running into the peer dependency issue. Users need to install peer dependencies themselves, which is a missing step here.
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from amazon-chime-sdk-component-library-react@2.2.0+c9ddf741
npm ERR! .yalc/amazon-chime-sdk-component-library-react
```

I will add a step in the local meeting demo running steps + the deployment steps. 
Could you please run below steps and let me know if they worked:
1. If you haven't already, [configure your AWS credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html).

2. Install [yalc](https://www.npmjs.com/package/yalc) to get the latest changes from the local component library.
`npm i yalc -g`

3. Clone the repo and change directory into the cloned repo.
```
git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
cd amazon-chime-sdk-component-library-react
```

4. Install root dependencies.
```
npm install
```

5. Install peer dependencies for the `amazon-chime-sdk-component-library-react`.
```
npm install --save amazon-chime-sdk-component-library-react amazon-chime-sdk-js styled-components styled-system
```

6. Navigate to the meeting demo folder and build the demo.
```
cd demo/meeting
npm run build
```

7. Next, move to the `serverless` directory under `demo/meeting/` and run the deploy script.
```
cd serverless
node ./deploy.js -r us-east-1 -b <YOUR-S3-BUCKET-NAME> -s <YOUR-CLOUDFORMATION-STACK-NAME>
```

**Comment by aburnson** [comment]
```
aburnson@ test % git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
Cloning into 'amazon-chime-sdk-component-library-react'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 8193 (delta 87), reused 168 (delta 72), pack-reused 7987
Receiving objects: 100% (8193/8193), 9.01 MiB | 4.22 MiB/s, done.
Resolving deltas: 100% (5024/5024), done.
aburnson@ test % cd amazon-chime-sdk-component-library-react
aburnson@ amazon-chime-sdk-component-library-react % npm install

added 2405 packages, and audited 2406 packages in 53s

found 0 vulnerabilities
aburnson@ amazon-chime-sdk-component-library-react % npm install --save amazon-chime-sdk-component-library-react amazon-chime-sdk-js styled-components styled-system

added 1 package, changed 2 packages, and audited 2407 packages in 4s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
aburnson@ amazon-chime-sdk-component-library-react % cd demo/meeting
aburnson@ meeting % npm run build

> chime-sdk-meeting-demo@0.1.0 build
> npm run deps && yalc add amazon-chime-sdk-component-library-react && npm install && npm run build:fast


> chime-sdk-meeting-demo@0.1.0 deps
> cd ../.. && npm run build && yalc publish


> amazon-chime-sdk-component-library-react@2.2.0 build
> rollup -c


src/index.ts → lib/index.js, lib/index.esm.js...
(!) Circular dependencies
src/index.ts -> src/components/ui/Chat/ChatBubble/ChatBubbleContainer.tsx -> src/index.ts
src/providers/AudioVideoProvider/index.tsx -> src/providers/MeetingProvider/index.tsx -> src/providers/AudioVideoProvider/index.tsx
src/providers/MeetingProvider/index.tsx -> src/providers/RosterProvider/index.tsx -> src/providers/MeetingProvider/index.tsx
...and 8 more
created lib/index.js, lib/index.esm.js in 57.1s
amazon-chime-sdk-component-library-react@2.2.0+b95af89e published in store.
Package amazon-chime-sdk-component-library-react@2.2.0+b95af89e added ==> /Users/aburnson/Desktop/test/amazon-chime-sdk-component-library-react/demo/meeting/node_modules/amazon-chime-sdk-component-library-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"^16.12.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from amazon-chime-sdk-component-library-react@2.2.0+b95af89e
npm ERR! .yalc/amazon-chime-sdk-component-library-react
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/aburnson/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aburnson/.npm/_logs/2021-04-05T23_35_00_644Z-debug.log
npm ERR! code 1
npm ERR! path /Users/aburnson/Desktop/test/amazon-chime-sdk-component-library-react/demo/meeting
npm ERR! command failed
npm ERR! command sh -c npm run deps && yalc add amazon-chime-sdk-component-library-react && npm install && npm run build:fast

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aburnson/.npm/_logs/2021-04-05T23_35_00_683Z-debug.log
```

**Comment by devalevenkatesh** [comment]
Confirmed with Andrew that he tried running this with NPM 7 and hence NPM tried installing peer dependencies automatically which ran into error. 

https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

Will work on a fix soon.

**Comment by schuettc** [comment]
> ```
> aburnson@ test % git clone https://github.com/aws/amazon-chime-sdk-component-library-react.git
> Cloning into 'amazon-chime-sdk-component-library-react'...
> remote: Enumerating objects: 206, done.

@aburnson 

You can use  `npm install --legacy-peer-deps` to resolve the issue until npm versioning can be resolved.  

https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-dependency-resolution-and-tree-design

**Comment by ltrung** [comment]
#488 has updated the react demo to 17 as well so you do not need --legacy-peer-deps anymore. Closing this issue.
