### ISSUE TITLE
getting issue after updating react scripts package

### ISSUE THREAD

**Issue by harishaventri** [aws/amazon-chime-sdk-component-library-react#728]
### What happened and what did you expect to happen?

Facing issue after upgrading the react-scripts package from 4.0.3 to 5.0.0. We are using create react app to build our chime app.
Following are the package.json details,
```
"dependencies": {
    "@craco/craco": "6.1.2",
    "@fortawesome/fontawesome-pro": "^5.15.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/pro-duotone-svg-icons": "^5.15.3",
    "@fortawesome/pro-light-svg-icons": "^5.15.3",
    "@fortawesome/pro-regular-svg-icons": "^5.15.3",
    "@fortawesome/pro-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@jinsung.lim/tailwindcss-filters": "^0.1.1",
    "@tailwindcss/forms": "^0.3.3",
    "@tailwindcss/postcss7-compat": "^2.2.2",
    "@tailwindui/react": "^0.1.1",
    "@tensorflow-models/body-pix": "^2.2.0",
    "@tensorflow/tfjs": "^3.7.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^13.1.9",
    "@use-it/interval": "^1.0.0",
    "amazon-chime-sdk-component-library-react": "2.11.1",
    "amazon-chime-sdk-js": "2.24.0",
    "autoprefixer": "^10.4.2",
    "axios": "^0.21.4",
    "browserslist": "^4.16.6",
    "dotenv": "^10.0.0",
    "flow-bin": "^0.152.0",
    "glob-parent": "^6.0.0",
    "husky": "^6.0.0",
    "i18next": "^20.3.2",
    "i18next-http-backend": "^1.2.6",
    "jsonwebtoken": "^8.5.1",
    "lint-staged": "^11.0.0",
    "markdown-it": "^12.0.6",
    "moment": "^2.29.1",
    "normalize-url": "^6.0.1",
    "path-browserify": "^1.0.1",
    "postcss": "^8.4.5",
    "prettier": "^2.3.1",
    "react": "^17.0.2",
    "react-circular-progressbar": "^2.0.4",
    "react-device-detect": "^1.17.0",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.11.0",
    "react-id-generator": "^3.0.1",
    "react-player": "^2.9.0",
    "react-recipes": "^1.1.1",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^5.0.0",
    "react-speech-recognition": "^3.8.2",
    "react-tooltip": "^4.2.21",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "tailwind-scrollbar-hide": "^1.0.3",
    "tailwindcss": "^3.0.13",
    "universal-cookie": "^4.0.4",
    "uuid": "^8.3.2",
    "video.js": "^7.15.0",
    "web-vitals": "^2.0.1"
  },
"devDependencies": {
    "@babel/preset-env": "^7.14.5",
    "@babel/preset-react": "^7.14.5",
    "@commercetools/enzyme-extensions": "^5.0.0",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.2",
    "@babel/eslint-parser": "^7.5.4",
    "css-what": "^5.0.1",
    "enzyme": "^3.11.0",
    "enzyme-to-json": "^3.6.2",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "jest-fetch-mock": "^3.0.3",
    "jest-localstorage-mock": "^2.4.14",
    "npm-force-resolutions": "0.0.10",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^7.2.3",
    "react-test-renderer": "^17.0.2",
    "serve": "^13.0.2",
    "stylelint": "^13.13.1",
    "stylelint-config-standard": "^22.0.0"
  }
```

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

On running the app 
npm start 

### Amazon Chime SDK React Components Library version

2.11.1

### What browsers are you seeing the problem on?

chrome

### Browser version

94.0.4606.71 

### Device Information

Ubuntu 20.04

### Browser console logs

Compiled with problems:X

ERROR in ./node_modules/react-circular-progressbar/dist/styles.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/react-circular-progressbar/dist/styles.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./node_modules/video.js/dist/video-js.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/video.js/dist/video-js.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/App.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/App.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/components/AventriSpinner.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/components/AventriSpinner.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/components/Loading.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/components/Loading.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/containers/demo/demo.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/containers/demo/demo.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/containers/diagnosticlog-popup/diagnostic-log-popup.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/containers/diagnosticlog-popup/diagnostic-log-popup.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/containers/meeting-test/meeting-test.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/containers/meeting-test/meeting-test.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/containers/meeting/meeting.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/containers/meeting/meeting.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/@tailwindcss/forms/src/index.js:34:63
    at registerPlugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:605:61)
    at createContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:762:5)
    at Object.getContext (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:817:19)
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:142:53
    at /home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:41:11
    at plugins (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/aventri/Downloads/aventri/virtual-meeting-frontend/node_modules/postcss/lib/lazy-result.js:221:30)

**Comment by jing-chen1** [comment]
Hi @harishaventri,

Thanks for your interest in Chime React Component Library. After going through the dependencies you provided and comparing them with our current dependencies, I find it may be related to the incompatible dependency issue.
```
// There are different major versions in the same dependency, which would cause problems
// The left version is for our Chime React Component Library, and right one is for your app
autoprefixer "^9.8.6", "^10.4.2",
dotenv: "8.6.0", "^10.0.0",
glob-parent: "~5.1.0",  "^6.0.0",
normalize-url: "^4.1.0", "^6.0.1",
path-browserify: "0.0.1", "^1.0.1",
postcss: "^7.0.5", "^8.4.5",
react-router: "^6.0.0", "^5.2.0",
react-router-dom: "^6.0.0", "^5.2.0",
eslint-plugin-prettier: "^4.0.0", "^3.4.0"
```
You may want to upgrade/downgrade these dependencies to get your Chime app working, or you can also wait for us to upgrade dependencies.

**Comment by devalevenkatesh** [comment]
Closing this issue due to inactivity, please feel free to re-open with an update if still an issue, thanks!
