### ISSUE TITLE
Issue in npm start

### ISSUE THREAD

**Issue by deepaksrinivasan27** [aws/amazon-chime-sdk-component-library-react#900]
### What happened and what did you expect to happen?

Build errors at npm start at the root of the directory. 

ModuleNotFoundError: Module not found: Error: Can't resolve './version' in 'C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning'
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\Compilation.js:2022:28)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:817:13)
    at eval (eval at create (C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:10:1)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:275:22)
    at eval (eval at create (C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:9:1)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:448:22)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:118:11)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:689:25)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:893:8)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:1013:5)
resolve './version' in 'C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning'
  using description file: C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\package.json (relative path: ./src/versioning)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\package.json (relative path: ./src/versioning/version)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.cjs doesn't exist
      as directory
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

npm start

### Amazon Chime SDK React Components Library version

"version": "3.8.0"

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 114.0.5735.90 

### Device Information

Windows

### Browser console logs

ModuleNotFoundError: Module not found: Error: Can't resolve './version' in 'C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning'
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\Compilation.js:2022:28)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:817:13)
    at eval (eval at create (C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:10:1)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:275:22)
    at eval (eval at create (C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:9:1)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:448:22)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:118:11)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:689:25)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:893:8)
    at <anonymous> (c:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\node_modules\webpack\lib\NormalModuleFactory.js:1013:5)
resolve './version' in 'C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning'
  using description file: C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\package.json (relative path: ./src/versioning)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\package.json (relative path: ./src/versioning/version)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version.cjs doesn't exist
      as directory
        C:\CDK\ARC-Chime\amazon-chime-sdk-component-library-react\src\versioning\version doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Comment by abhi1101stellar** [comment]
Try installing webpack for your project. You can try my working config done
`const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const Dotenv = require('dotenv-webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin')

module.exports = {
    entry: './src/index.js',
    resolve: {
        extensions: ['.js', '.jsx' , '.ts' , '.tsx']
    },
    output: {
        path: path.resolve(__dirname, 'build'), // change this
        publicPath: '/',
        filename: 'bundle.js'
    },
    devServer: {
        static: './',
        port: 3000,
        hot: true,
        liveReload: true,
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx|ts|tsx)$/,
                exclude: /node_modules/,
                use: ['babel-loader']
            },
            {
                test: /\.less$/,
                use: [
                    'style-loader',
                    'css-loader',
                    
                ],
            },
            {
                test: /\.(ico)$/i,
                loader: 'file-loader',
                options: {
                  name: '[name].[ext]',
                  outputPath: 'icons',
                },
            },
        ]
    },
    devtool: 'inline-source-map',
    plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve('./public/index.html'),
        }),
        new Dotenv(),
        new CopyWebpackPlugin({
            patterns: [
              { from: 'public/icons', to: '' },
            ],
          }),
          new ErrorOverlayPlugin(),
    ]
};`

**Comment by devalevenkatesh** [comment]
Created a PR to update the README, but suggest running `npm run build` first after cloning and then `npm start` so that the storybook runs successfully. Since, build is not done, the autogenerated `versioning` file does not exist and hence storybook fails to build successfully as well.
